version: 2.1
jobs:
  build-openvisus-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.large  # see https://circleci.com/docs/2.0/arm-resources/, seems to have problems with medium
    parameters:
      python-version:
        type: string 
    parallelism: 1 # I don't think I can execute all the jobs in parallel      
    steps:
      - checkout
      - run:
          name: Build OpenVisus
          no_output_timeout: 50m
          command: |
                    set -e
                    set -x
                    
                    # this will generate all ARM configurations (cpython nogui; conda nogui)
                    PYTHON_VERSION=<< parameters.python-version >>
                    docker run --rm -v ${PWD}:/home/OpenVisus -w /home/OpenVisus \
                      -e BUILD_DIR=build_docker \
                      -e VISUS_GUI=0 -e VISUS_SLAM=0 -e VISUS_MODVISUS=0 \
                      -e PYTHON_VERSION=$PYTHON_VERSION \
                      -e PYPI_USERNAME=${PYPI_USERNAME} -e PYPI_PASSWORD=${PYPI_PASSWORD} \
                      -e ANACONDA_TOKEN=${ANACONDA_TOKEN} \
                      nsdf/manylinux2014_aarch64:latest bash scripts/build_linux.sh       

                    # deploy modvisus
                    GIT_TAG=`git describe --tags --exact-match 2>/dev/null || true`
                    if [[ "$GIT_TAG" !="" &&  "$PYTHON_VERSION" == "3.9" ]] ; then
                      sleep 30 # give time for pip package to be ready
                      pushd  Docker/mod_visus
                      docker build --tag visus/mod_visus_aarch64:$GIT_TAG --tag visus/mod_visus_aarch64:latest --build-arg TAG=$GIT_TAG .
                      echo ${DOCKER_TOKEN} | docker login -u=${DOCKER_USERNAME} --password-stdin
                      docker push visus/visus/mod_visus_aarch64:$GIT_TAG
                      docker push visus/visus/mod_visus_aarch64:latest
                      popd
                    fi  
          
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-openvisus-arm64:
          matrix:
            parameters:
              python-version: ['3.7', '3.8', '3.9' ,'3.10' ]




           

      

