version: 2.1
jobs:
  build-openvisus-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    parameters:
      python-version:
        type: string       
    steps:
      - checkout
      - run:
          name: Build OpenVisus cpython
          no_output_timeout: 50m
          command: |
            # this will generate all ARM configurations (cpython nogui; conda nogui)
            PYTHON_VERSION=<< parameters.python-version >>
            docker run --rm -v ${PWD}:/home/OpenVisus -w /home/OpenVisus \
              -e BUILD_DIR=build_docker \
              -e VISUS_GUI=0 -e VISUS_SLAM=0 -e VISUS_MODVISUS=0 \
              -e PYTHON_VERSION=$PYTHON_VERSION \
              -e PYPI_USERNAME=${PYPI_USERNAME} -e PYPI_PASSWORD=${PYPI_PASSWORD} \
              -e DOCKER_USERNAME=${DOCKER_USERNAME} -e DOCKER_TOKEN=${DOCKER_TOKEN} \
              -e ANACONDA_TOKEN=${ANACONDA_TOKEN} \
              nsdf/manylinux2014_aarch64:latest bash scripts/build_linux.sh               

              
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-openvisus-arm64:
          matrix:
            parameters:
              python-version: ['3.7', '3.8', '3.9' ,'3.10' ]




           

      

