version: 2.1
jobs:
  build-openvisus-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.large  # see https://circleci.com/pricing/#compute-options-table
    parameters:
      python-version:
        type: string
    steps:
      - checkout
      - run:
          name: Build openvisus
          command: |
                   export PYTHON_VERSION=<< parameters.python-version >>
                   export VISUS_GUI=0
                   export VISUS_SLAM=0
                   export VISUS_MODVISUS=0 
                   export DOCKER_IMAGE=nsdf/manylinux2014_aarch64:latest
                   export DOCKER_MODVISUS_IMAGE=visus/mod_visus_aarch64
                   source scripts/linux.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-openvisus-arm64:
          matrix:
            parameters:
              python-version: ['3.7', '3.8', '3.9' ,'3.10' ]
