version: 2.1
jobs:
  build-openvisus:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    parameters:
      python-version:
        type: string       
    steps:
      - checkout
      - run:
          name: Build OpenVisus
          command: |
            set -e
            set -x    
            echo $PWD      
            PYTHON_VERSION=<< parameters.python-version >>
            sudo docker run --rm \
              -v $PWD:/home/OpenVisus -w /home/OpenVisus \
              -e PYTHON_VERSION=${PYTHON_VERSION} -e PYPI_PASSWORD=${PYPI_PASSWORD} -e ANACONDA_TOKEN=${ANACONDA_TOKEN}  \
              nsdf/manylinux2014_aarch64:latest bash scripts/build_linux.arm64.sh   
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-openvisus:
          matrix:
            parameters:
              python-version: ['3.7', '3.8', '3.9' ,'3.10' ]




           

      

