name: build-ubuntu
on: [push]
jobs:

  example:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
    
      - name: Test
        run: |
            docker run --rm multiarch/ubuntu-core:arm64-wily 'bash -c "uname -a"'
