name: build-ubuntu
on: [push]
jobs:

  Build:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9'] 
        VISUS_GUI: ['1', '0']
     
    steps:
    - name: git clone OpenVisus
      uses: actions/checkout@v2
      
    - name: filter CI
      uses: mstachniuk/ci-skip@v1
      with:
        fail-fast: true
        exit-code: 0
        commit-filter: '[no-ci];[windows];[macos];[conda]'
        commit-filter-separator: ';'

    - name: Install CPython 
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }} 
        architecture: 'x64'

    - name: Compile OpenVisus  
      shell: bash -l {0}
      run: |
           PLATFORM_NAME=manylinux2010_x86_64
           docker run \
             -e PYTHON_VERSION=${{ matrix.python-version }} \
             -e VISUS_GUI=${{ matrix.VISUS_GUI }} \
             -e VISUS_SLAM=${{ matrix.VISUS_GUI }} \
             -e Qt5_DIR=/opt/qt512 \
             -e VISUS_MODVISUS=1 \
             -e PYPI_USERNAME=${{ secrets.PYPI_USERNAME }} \
             -e PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }} \
             -d PLATFORM_NAME=${PLATFORM_NAME} \
             -e DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} \
             -e DOCKER_TOKEN=${{ secrets.DOCKER_TOKEN }} \
             -v ${PWD}:${PWD}  \
             -w ${PWD} \
             visus/${PLATFORM_NAME} \
             /bin/bash -c "./scripts/build_openvisus.sh"
