name: build-ubuntu
on: [push]
jobs:

  build-job:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.8',] 
        specs: [
            {key: 'cpyth-ngui-amd64',  platform: 'linux/amd64' , conda: '0', gui: '0', docker-image: 'visus/portable-linux-binaries_x86_64:2.0', qt5-dir: ''                      , wheel-platform-name: 'manylinux2010_x86_64'  },
            {key: 'cpyth-ygui-amd64',  platform: 'linux/amd64' , conda: '0', gui: '1', docker-image: 'visus/portable-linux-binaries_x86_64:2.0', qt5-dir: '/opt/qt512'            , wheel-platform-name: 'manylinux2010_x86_64'  },
            {key: 'cpyth-ngui-arm64',  platform: 'linux/arm64' , conda: '0', gui: '0', docker-image: 'nsdf/manylinux2014_aarch64:latest'       , qt5-dir: ''                      , wheel-platform-name: 'manylinux2014_aarch64' },
            
            {key: 'conda-ygui-amd64',  platform: 'linux/amd64' , conda: '1', gui: '1', docker-image: 'condaforge/mambaforge:latest'            , qt5-dir: 'lib/cmake/Qt5'         , wheel-platform-name: ''  },
            {key: 'conda-ngui-arm64',  platform: 'linux/arm64' , conda: '1', gui: '0', docker-image: 'condaforge/mambaforge:latest'            , qt5-dir: ''                      , wheel-platform-name: ''  }
          ]
     
    steps:
    
      # ////////////////////////////////////////////////////////////
    
    - name: git clone OpenVisus
      uses: actions/checkout@v2

    - name: Set up QEMU
      if:  matrix.specs.platform=='linux/arm64'
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
        
    - name: Set up Docker Buildx
      if:  matrix.specs.platform=='linux/arm64'
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Available platforms
      if:  matrix.specs.platform=='linux/arm64'
      run: echo ${{ steps.buildx.outputs.platforms }}
                
    # disabled for testing only
    - name: Test AARM64
      if: ${{ false }}
      run: |
          set -e
          set -x
          cat <<EOF >test.sh
          #!/bin/bash
          uname -a
          EOF
          docker run --platform linux/arm64 -v $PWD:$PWD -w $PWD --rm nsdf/manylinux2014_aarch64:latest bash test.sh


      # ////////////////////////////////////////////////////////////

    - name: Compile OpenVisus on cpython
      if:  matrix.specs.conda == '0' && ${{ false }}
      shell: bash
      run: docker run --rm --platform ${{ matrix.specs.platform }} -v $PWD:/home/OpenVisus -w /home/OpenVisus ${{ matrix.specs.docker-image }} bash /home/OpenVisus/.github/workflows/build-ubuntu-cpython.sh

      # ////////////////////////////////////////////////////////////

    - name: Compile OpenVisus on conda 
      shell: bash
      if:  matrix.specs.conda == '1'
      run: docker run --rm --platform ${{ matrix.specs.platform }} -v $PWD:/home/OpenVisus -w /home/OpenVisus ${{ matrix.specs.docker-image }} bash /home/OpenVisus/.github/workflows/build-ubuntu-conda.sh


