name: build-openvisus
on: [push]
jobs:
  build-1:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false  
      matrix:
        type: [ "cpython" , "conda" ]
        os: [ "windows" , "macos" ]
        python-version: [ '3.7', '3.8', '3.9' , '3.10' ]
    steps:
    - name: git clone OpenVisus
      uses: actions/checkout@v2
    - name: Compile (cpython)
      shell: bash
      run: |
           set -ev
           export PYTHON_VERSION=${{ matrix.python-version }}
           export PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
           export PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
           export ANACONDA_TOKEN=${{ secrets.ANACONDA_TOKEN }}
           source ./scripts/${{ matrix.type }}.${{ matrix.os }}.sh
  build-2:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false  
      matrix:
        os: ["ubuntu" ]
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
    steps:
    - name: git clone OpenVisus
      uses: actions/checkout@v2
    - name: Compile cpython
      shell: bash
      run: |
           set -ev
           export PYTHON_VERSION=${{ matrix.python-version }}
           export PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
           export PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
           export ANACONDA_TOKEN=${{ secrets.ANACONDA_TOKEN }}
           export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
           export DOCKER_TOKEN=${{ matrix.python-version }}
           export DOCKER_IMAGE=visus/portable-linux-binaries_x86_64:4.1
           export DOCKER_MODVISUS_IMAGE=visus/mod_visus
           source scripts/${{ matrix.os }}.sh










