name: build-conda

on: [push]

jobs:

  # ///////////////////////////////////////////////////////////////
  Build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9'] 
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    steps:
    
    # ____________________________________________ CLONE OPENVISUS
    
    - name: git clone OpenVisus
      uses: actions/checkout@v2    

    - name: git clone opsray for windows
      if: matrix.os == 'windows-latest'
      uses: nick-invision/retry@v1
      with:
        max_attempts: 3
        timeout_minutes: 4
        retry_wait_seconds: 5
        command: 'rm -Rf ExternalLibs/ospray_win && git clone https://github.com/sci-visus/ospray_win.git  ExternalLibs/ospray_win'    

    # ____________________________________________ INSTALL SDK 10.9
    
    - name: Install SDK 10.9 for macos 
      if: matrix.os == 'macos-latest'
      uses: nick-invision/retry@v1
      with:
        max_attempts: 3
        timeout_minutes: 5
        retry_wait_seconds: 5
        command: 'cd /tmp && rm -Rf MacOSX-SDKs && git clone https://github.com/phracker/MacOSX-SDKs.git'      

    # ____________________________________________ INSTALL CONDA
    - name: Install and confifure Miniconda 
      uses: conda-incubator/setup-miniconda@v2
      continue-on-error: true # if fails the cleaning process
      with:
        miniconda-version: 'latest'
        python-version: ${{ matrix.python-version }}
        activate-environment: tmp
        auto-update-conda: false
        channels: conda-forge,defaults

    - name: Configure Miniconda 
      shell: bash -l {0}
      run: |
           conda config --set always_yes yes --set changeps1 no --set anaconda_upload no   1>/dev/null
           conda install conda                                                             1>/dev/null

    # ____________________________________________ INSTALL SWIG 

    - name: Install Swig for windows
      if: matrix.os == 'windows-latest'
      shell: bash -l {0}
      run: curl -L --insecure https://cfhcable.dl.sourceforge.net/project/swig/swigwin/swigwin-4.0.2/swigwin-4.0.2.zip -O  && unzip swigwin-4.0.2.zip # problems with choco

    - name: Install Swig for macos
      if: matrix.os == 'macos-latest'
      shell: bash -l {0}
      run: brew install swig
      
      
    # ____________________________________________ INSTALL CMAKE
    
    - name: Install CMake for windows
      if: matrix.os == 'windows-latest'
      shell: bash -l {0}    
      run: conda install -c conda-forge cmake
    
    - name: Install CMake for macos
      if: matrix.os == 'macos-latest'
      shell: bash -l {0}    
      run: brew install cmake # problems with conda
      
    - name: Install CMake for Linux
      if: matrix.os == 'ubuntu-latest' 
      shell: bash -l {0}    
      run: conda install -c conda-forge cmake     

    # ____________________________________________ INSTALL PyQt

    - name: Install PyQt for windows
      if: matrix.os == 'windows-latest'
      shell: bash -l {0}
      run: conda install -y pyqt=5.9  # -c conda-forge -y pyqt=5.12 (they rename DLLS, like Qt5Core.dll->Qt5Core_conda.dll))
           
    - name: Install PyQt for osx
      if: matrix.os == 'macos-latest'
      shell: bash -l {0}
      run: conda install -c conda-forge -y pyqt=5.12

    # ____________________________________________ COMPILE OPENVISUS
    
    - name: Compile OpenVisus on windows
      if: matrix.os == 'windows-latest'    
      shell: bash -l {0}
      run: |
           mkdir -p build
           cd build
           cmake -G "Visual Studio 16 2019" -A "x64" -DQt5_DIR="${CONDA_PREFIX}/Library/lib/cmake/Qt5" -DPython_EXECUTABLE=$(which python) -DSWIG_EXECUTABLE=../swigwin-4.0.2/swig.exe -DVISUS_SLAM=1 ../
           cmake --build . --target ALL_BUILD --config Release --parallel 4
           cmake --build . --target install   --config Release

    - name: Compile OpenVisus on macos
      if: matrix.os == 'macos-latest'
      shell: bash -l {0}
      run: |
           mkdir -p build
           cd build
           cmake -GXcode -DQt5_DIR="${CONDA_PREFIX}/lib/cmake/Qt5" -DCMAKE_OSX_SYSROOT="/tmp/MacOSX-SDKs/MacOSX10.9.sdk"  -DPython_EXECUTABLE=$(which python) -DVISUS_SLAM=1  ../
           cmake --build ./ --target ALL_BUILD --config Release --parallel 4 
           cmake --build ./ --target install   --config Release 

    - name: Compile OpenVisus on ubuntu
      if: matrix.os == 'ubuntu-latest' 
      shell: bash -l {0}
      run: |
           # i can use the pyqt one, but I would need to share the directory to docker, for simplicity I'm not doing it
           docker run -e PYTHON_VERSION=${{ matrix.python-version }} -e Qt5_DIR=/opt/qt512 -v ${PWD}:${PWD}  -w ${PWD} visus/portable-linux-binaries /bin/bash -c "./scripts/build_linux.sh"
           sudo chown -R root:root  build
           sudo chmod -R a+rwx      build

    # ____________________________________________ TEST
    
    - name: Test OpenVisus 
      shell: bash -l {0}
      run: |
           set -e  # stop or error
           set -x  # very verbose
           which python
           cd build/Release/OpenVisus
           export PYTHONPATH=../
           python -m OpenVisus configure  || true  # segmentation fault problem on linux
           python -m OpenVisus test
           python -m OpenVisus test-gui

    # ____________________________________________ DISTRIB
    
    - name: Distrib OpenVisus
      shell: bash -l {0}   
      run: |
           set -e  # stop or error
           set -x  # very verbose
           cd build/Release/OpenVisus
           conda install --yes anaconda-client  1>/dev/null  || true
           conda install --yes conda-build      1>/dev/null  || true
           conda install --yes wheel            1>/dev/null  || true
           rm -Rf $(find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2")  || true
           python setup.py -q bdist_conda 1>/dev/null
           CONDA_FILENAME=$(find ${CONDA_PREFIX} -iname "openvisus*.tar.bz2"  | head -n 1)       
           GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || true)
           if [[ "${GIT_TAG}" != ""  ]] ; then
             export PATH=$HOME/anaconda3/bin:$PATH
             anaconda --verbose --show-traceback  -t ${{ secrets.ANACONDA_TOKEN }}   upload "${CONDA_FILENAME}"
           fi
