name: build-conda-ubuntu
on: [push]
jobs:
  Build:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false  
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9'] 
    steps:
    
    - name: git clone OpenVisus
      uses: actions/checkout@v2
      
    - name: filter CI
      uses: mstachniuk/ci-skip@v1
      with:
        fail-fast: true
        exit-code: 0
        commit-filter: '[no-ci];[windows];[macos];[cpython]'
        commit-filter-separator: ';'

    - name: Compile OpenVisus x86_64
      shell: bash -l {0}
      run: | 
           docker run \
             -e PYTHON_VERSION=${{ matrix.python-version }} \
             -e VISUS_GUI=0 \
             -e VISUS_SLAM=0 \
             -e VISUS_MODVISUS=0 \
             -e ANACONDA_TOKEN=${{ secrets.ANACONDA_TOKEN }} \
             -v ${PWD}:${PWD}  \
             -w ${PWD} \
             visus/manylinux2010_x86_64 \
             /bin/bash -c "./scripts/build_openvisus.sh"


