name: build-ubuntu
on: [push]
jobs:

  example:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
    
      - name: Test
        run: |
        
            cat <<EOF >test.sh
            #!/bin/bash
            set -e
            set -x
            uname -a
            EOF
            chmod a+x ./test.sh
                    
            docker run --platform linux/arm64 -v $PWD/test.sh:/tmp/test.sh -w /tmp --rm --entrypoint "bast test.sh" nsdf/manylinux2014_aarch64:latest
