name: build-openvisus
on: [push]
jobs:
  build-openvisus-windows-cpython:
    runs-on: "windows-latest"
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]  
    steps:
    - name: git clone OpenVisus
      uses: actions/checkout@v2
    - name: Compile (cpython)
      shell: bash
      run: |
           export PYTHON_VERSION=${{ matrix.python-version }}
           export PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
           export PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
           export PYTHON=${pythonLocation}/python
           source ./scripts/cpython.windows.sh
  build-openvisus-windows-conda:
    runs-on: "windows-latest"
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ] 
    steps:
    - name: git clone OpenVisus
      uses: actions/checkout@v2
    - name: Compile (conda)
      shell: bash 
      run: |
           export PYTHON_VERSION=${{ matrix.python-version }}
           export ANACONDA_TOKEN=${{ secrets.ANACONDA_TOKEN }}
           source scripts/conda.windows.sh
  build-openvisus-macos-cpython:
    runs-on: "macos-latest"
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10']  
    steps:
    - name: git clone OpenVisus
      uses: actions/checkout@v2
    - name: Compile cpython
      env:
      shell: bash
      run: |
           export PYTHON_VERSION=${{ matrix.python-version }}
           export PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
           export PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
           source scripts/cpython.windows.sh
  build-openvisus-macos-conda:
    runs-on: "macos-latest"
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10']
    steps:
    - name: git clone OpenVisus
      uses: actions/checkout@v2
    - name: Build (conda)
      shell: bash
      run: |
           export PYTHON_VERSION=${{ matrix.python-version }}
           export ANACONDA_TOKEN=${{ secrets.ANACONDA_TOKEN }}
           source scripts/conda.macos.sh
  build-openvisus-ubuntu:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
    steps:
    - name: git clone OpenVisus
      uses: actions/checkout@v2
    - name: Compile cpython
      shell: bash
      run: |
           export PYTHON_VERSION=${{ matrix.python-version }}
           export PYPI_USERNAME=${{ secrets.PYPI_USERNAME }}
           export PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
           export ANACONDA_TOKEN=${{ secrets.ANACONDA_TOKEN }}
           export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
           export DOCKER_TOKEN=${{ matrix.python-version }}
           export PULL_IMAGE=visus/portable-linux-binaries_x86_64:4.1
           export PUSH_IMAGE=visus/mod_visus
           source scripts/linux.sh










