name: build-cpython

on: [push]

jobs:

  # ///////////////////////////////////////////////////////////////
  Build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9'] 
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
        VISUS_GUI: ['1', '0']
     
    steps:
    
    - name: git clone OpenVisus
      uses: actions/checkout@v2
     
    - name: git clone opsray for windows
      if: matrix.os == 'windows-latest' && matrix.VISUS_GUI == '1'
      uses: nick-invision/retry@v1
      with:
        max_attempts: 3
        timeout_minutes: 4
        retry_wait_seconds: 5
        command: 'rm -Rf ExternalLibs/ospray_win && git clone https://github.com/sci-visus/ospray_win.git  ExternalLibs/ospray_win'
        
    - name: Install CMake for windows
      uses: lukka/get-cmake@latest
      if: matrix.os == 'windows-latest' 
      
    - name: Install CMake for macos
      uses: lukka/get-cmake@latest
      if: matrix.os == 'macos-latest'

    - name: Install Swig for windows
      if: matrix.os == 'windows-latest'
      shell: bash -l {0}
      run: curl -L --insecure https://cfhcable.dl.sourceforge.net/project/swig/swigwin/swigwin-4.0.2/swigwin-4.0.2.zip -O  && unzip swigwin-4.0.2.zip # problems with choco

    - name: Install Swig for macos
      if: matrix.os == 'macos-latest'
      shell: bash -l {0}
      run: brew install swig
    
    - name: Install SDK 10.9 for macos 
      if: matrix.os == 'macos-latest'
      uses: nick-invision/retry@v1
      with:
        max_attempts: 3
        timeout_minutes: 5
        retry_wait_seconds: 5
        command: 'cd /tmp && rm -Rf MacOSX-SDKs && git clone https://github.com/phracker/MacOSX-SDKs.git'

    - name: Install CPython 
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }} 
        architecture: 'x64'

    - name: Install Qt for windows
      if: matrix.os == 'windows-latest' && matrix.VISUS_GUI == '1'
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.8'
        arch: 'win64_msvc2017_64'
        install-deps: 'true'
        dir: C:\
        setup-python: 'false' 
        
    - name: Install Qt for macos
      if: matrix.os == 'macos-latest'  && matrix.VISUS_GUI == '1'
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.8'
        target: 'desktop'
        install-deps: 'true'  
        dir: /tmp
        setup-python: 'false' 

    - name: Install glu on ubuntu
      if: matrix.os == 'ubuntu-latest'  && matrix.VISUS_GUI == '1' 
      shell: bash -l {0}
      run: |
           set -e
           set -x
           sudo apt-get update -y 1>/dev/null
           sudo apt-get install -y libglu1-mesa-dev 1>/dev/null

    - name: Compile OpenVisus on windows
      if: matrix.os == 'windows-latest'
      shell: bash -l {0}
      run: |
           set -e
           set -x
           mkdir -p build 
           cd build
           cmake -G "Visual Studio 16 2019" -A "x64" \
             -DVISUS_GUI=${{ matrix.VISUS_GUI }} \
             -DVISUS_SLAM=${{ matrix.VISUS_GUI }} \
             -DQt5_DIR="${Qt5_Dir}/lib/cmake/Qt5" \
             -DPython_EXECUTABLE=${pythonLocation}/python.exe  \
             -DSWIG_EXECUTABLE=../swigwin-4.0.2/swig.exe \
             ../
           cmake --build . --target ALL_BUILD --config Release --parallel 4
           cmake --build . --target install   --config Release

    - name: Compile OpenVisus on macos
      if: matrix.os == 'macos-latest'
      shell: bash -l {0}
      run: |
           mkdir -p build 
           cd build
           cmake -GXcode  \
             -DVISUS_GUI=${{ matrix.VISUS_GUI }} \
             -DVISUS_SLAM=${{ matrix.VISUS_GUI }} \
             -DQt5_DIR="${Qt5_Dir}/lib/cmake/Qt5" \
             -DCMAKE_OSX_SYSROOT="/tmp/MacOSX-SDKs/MacOSX10.9.sdk" \
             -DPython_EXECUTABLE=${pythonLocation}/python  \
             ../
           cmake --build ./ --target ALL_BUILD --config Release --parallel 4 
           cmake --build ./ --target install   --config Release 

    - name: Compile OpenVisus on ubuntu
      if: matrix.os == 'ubuntu-latest'
      uses: addnab/docker-run-action@v3
      with:
        image: visus/portable-linux-binaries
        shell: bash
        options: -v ${PWD}:/home/OpenVisus -w /home/OpenVisus
        run: |
            set -e 
            set -x  
            alias python3=python${{ matrix.python-version }}
            mkdir -p build 
            cd build
            cmake \
            	-DPython_EXECUTABLE=`which python${{ matrix.python-version }}` \
            	-DQt5_DIR=/opt/qt512  \
            	-DVISUS_GUI=${{ matrix.VISUS_GUI }}  \
            	-DVISUS_MODVISUS=1 \
            	-DVISUS_SLAM=${{ matrix.VISUS_GUI }} \
            	../
            make -j
            make install
            export PYTHONPATH=$PWD/Release
            python3 -m OpenVisus configure || true  # segmentation fault problem
            unset PYTHONPATH

    - name: Test OpenVisus 
      shell: bash -l {0}
      run: |
           set -e
           set -x
           alias python3=python${{ matrix.python-version }}
           which python
           export PYTHONPATH=$PWD/build/Release
           python3  -m OpenVisus configure  || true  # segmentation fault problem on linux
           python3  -m OpenVisus test
           if [[ "${{ matrix.VISUS_GUI }}" == "1" ]] ; then 
             python3  -m OpenVisus test-gui 
           fi

    - name: Distrib to PyPi
      shell: bash -l {0}
      run: |
           set -e
           set -x
           alias python3=python${{ matrix.python-version }}
           python3 -m pip install setuptools wheel twine --upgrade 1>/dev/null || true
           cd build/Release/OpenVisus
           
           # running setup to create the wheel
           Version=${{ matrix.python-version }}
           if [[  "${{ matrix.os }}" == "windows-latest" ]] ; then PLATFORM_NAME=win_amd64            ; fi
           if [[  "${{ matrix.os }}" == "macos-latest"   ]] ; then PLATFORM_NAME=macosx_10_9_x86_64   ; fi
           if [[  "${{ matrix.os }}" == "ubuntu-latest"  ]] ; then PLATFORM_NAME=manylinux2010_x86_64 ; fi
           python3 setup.py -q bdist_wheel --python-tag=cp${Version:0:1}${Version:2:1} --plat-name=${PLATFORM_NAME}
             
           GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || true)           
           if [[ "${GIT_TAG}" != "" ]] ; then
             echo "GIT_TAG $GIT_TAG"
             python3 -m twine upload --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --skip-existing  "dist/*.whl" 
           fi
             
    - name: Distrib to Docker
      if: matrix.os == 'ubuntu-latest' && matrix.VISUS_GUI == '0' && matrix.python-version=='3.7' 
      shell: bash -l {0}
      run: |
           set -e
           set -x
           alias python3=python${{ matrix.python-version }}
           TAG=`python3 Libs/swig/setup.py print-tag`
           echo "TAG=${TAG}" 
           cd Docker/mod_visus
           echo ${{ secrets.DOCKER_TOKEN }} | docker login -u=${{ secrets.DOCKER_USERNAME }} --password-stdin
           sleep 30 # give time pypi to get the pushed file
           docker build --tag visus/mod_visus:$TAG --tag visus/mod_visus:latest --build-arg TAG=$TAG .
           GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || true)
           if [[ "${GIT_TAG}" != "" ]] ; then
             echo "GIT_TAG $GIT_TAG"
             echo "Uploading  visus/mod_visus:$TAG to Docker"
             docker push visus/mod_visus:$TAG
             docker push visus/mod_visus:latest
           fi
